### ISSUE TITLE
Documentation is misleading.

### ISSUE THREAD

**Issue by lsmor** [input-output-hk/plutus-pioneer-program#4]
*Build the English Auction contract with cabal build* shouldn't be the first step, since it only works if you have cabal in your system **out of nix**. Considering that pretty much everyone is building plutus with nix, and the build includes cabal and all necesary libraries, building the contract should after initializing the nix-shell

**Comment by kevinhammond** [comment]
There can, of course, be issues with cabal/ghc versions/installations if you do this outside the nix shell, so you can get stuck on step 1

For beginners (or even those like me who have multiple conflicting development installations), it's probably easier to install Nix and Plutus first, start the shell, then build the contract.

Maybe also give a built version of the contract for those who are unable to do the build?

**Comment by kevinhammond** [comment]
As noted in another thread, you need `ghc-8.10.2 ` from a clean installation for this to work (prior Haskell platform installs could get you into trouble, for example).  Since this is really optional for the rest of the exercise, it would be best for most people to skip this step (or try it later once they've got the basics working).

**Comment by mateusap1** [comment]
I don't know why that happened, I didn't meant to reference this issue
